<template>
  <section class="rbac-page">
    <header class="page-head"><div><router-link to="/super-admin/rbac">← 返回权限组织</router-link><h2>职位权限</h2></div><div class="object-switch"><div class="object-badge"><small>当前对象 · 职位</small><strong>{{ selectedPosition ? `${selectedPosition.name} · ${selectedPosition.department_name || '未分部门'}` : '请选择职位' }}</strong></div><select v-model.number="selectedPositionId" @change="loadPosition"><option v-for="p in positions" :key="p.id" :value="p.id">{{ p.name }} / {{ p.department_name || '未分部门' }}</option></select></div></header>
    <div v-if="error" class="banner banner--error">{{ error }}</div><div v-if="message" class="banner">{{ message }}</div>
    <section class="panel workbench">
      <div class="permission-pane"><div class="pane-title"><div><strong>授权边界内权限</strong><span>按业务域分组勾选</span></div></div>
        <div v-if="hiddenCount" class="boundary-note">医疗 / 仓储等 {{ hiddenCount }} 项权限不在此职位授权边界内，已隐藏</div>
        <div class="permission-groups"><section v-for="group in groups" :key="group.name"><h3>{{ group.name }}</h3><div class="permission-list"><label v-for="key in group.keys" :key="key" class="permission-item" :class="{active:key===activeKey}" @mouseenter="activeKey=key"><input type="checkbox" :checked="selected.includes(key)" @focus="activeKey=key" @change="toggle(key)"/><span>{{ label(key) }}</span></label></div></section></div>
        <div class="actions"><button class="button" :disabled="!selectedPositionId" @click="openDiff">保存职位权限</button><button class="button button--ghost danger-button" :disabled="!selectedPositionId" @click="confirmReset">重置为默认最低权限</button></div>
      </div>
      <aside class="help"><strong>权限说明</strong><template v-if="activeMeta"><h3>{{ activeMeta.label }}</h3><code>{{ activeKey }}</code><p>{{ activeMeta.desc }}</p><div class="boundary">能力边界：仅在当前职位允许的业务域内生效，数据范围仍由组织范围控制。</div><div v-if="activeMeta.danger" class="warning">⚠ 高危权限：授予前请确认岗位确有需要。</div></template><p v-else class="empty">将鼠标移到或聚焦任一权限，这里会显示中文含义与能力边界。</p></aside>
    </section>
    <PermissionDiffDialog :open="diffOpen" title="确认职位权限差异" :added="added" :removed="removed" :saving="saving" @cancel="diffOpen=false" @confirm="save" />
  </section>
</template>
<script lang="ts">
import { computed, defineComponent, onMounted, ref } from "vue";
import PermissionDiffDialog from "@/modules/super-admin/components/PermissionDiffDialog.vue";
import { superAdminApi } from "@/modules/super-admin/api/superAdminApi";
import type { RbacPosition } from "@/modules/super-admin/api/types";
import { GROUP_ORDER, PERMISSION_META, permissionGroups, permissionLabel } from "@/modules/super-admin/utils/permissionMeta";
export default defineComponent({name:"SuperAdminRbacPositions",components:{PermissionDiffDialog},setup(){
 const positions=ref<RbacPosition[]>([]),catalog=ref<string[]>([]),selected=ref<string[]>([]),snapshot=ref<string[]>([]),grantable=ref<string[]>([]);const selectedPositionId=ref(0),activeKey=ref(""),error=ref(""),message=ref(""),diffOpen=ref(false),saving=ref(false);
 const selectedPosition=computed(()=>positions.value.find(p=>p.id===selectedPositionId.value));const activeMeta=computed(()=>activeKey.value?(PERMISSION_META[activeKey.value]||{label:activeKey.value,desc:"暂无中文说明。",group:"其他"}):null);const visibleKeys=computed(()=>Array.from(new Set([...grantable.value,...selected.value])));const groups=computed(()=>permissionGroups(visibleKeys.value));const hiddenCount=computed(()=>catalog.value.filter(k=>!visibleKeys.value.includes(k)).length);const added=computed(()=>selected.value.filter(k=>!snapshot.value.includes(k)));const removed=computed(()=>snapshot.value.filter(k=>!selected.value.includes(k)));
 const loadPosition=async()=>{if(!selectedPositionId.value)return;try{const data=await superAdminApi.getPositionPermissions(selectedPositionId.value);selected.value=[...data.permissions];snapshot.value=[...data.permissions];grantable.value=[...data.grantableKeys];activeKey.value=visibleKeys.value[0]||"";error.value=""}catch(e){error.value=e instanceof Error?e.message:"加载职位权限失败"}};
 const load=async()=>{try{[positions.value,catalog.value]=await Promise.all([superAdminApi.getRbacPositions(),superAdminApi.getPermissionCatalog()]);if(positions.value.length){selectedPositionId.value=positions.value[0].id;await loadPosition()}}catch(e){error.value=e instanceof Error?e.message:"加载权限数据失败"}};
 const toggle=(key:string)=>{activeKey.value=key;selected.value=selected.value.includes(key)?selected.value.filter(v=>v!==key):[...selected.value,key]};const openDiff=()=>{diffOpen.value=true};
 const save=async()=>{saving.value=true;try{await superAdminApi.updatePositionPermissions(selectedPositionId.value,selected.value);snapshot.value=[...selected.value];diffOpen.value=false;message.value="职位权限已保存";error.value=""}catch(e){error.value=e instanceof Error?e.message:"保存职位权限失败";diffOpen.value=false}finally{saving.value=false}};
 const confirmReset=async()=>{if(!window.confirm("将该职位恢复为系统默认最低权限，当前自定义权限会被替换。确认继续？"))return;try{await superAdminApi.resetPositionDefaults(selectedPositionId.value);await loadPosition();message.value="已重置为默认最低权限"}catch(e){error.value=e instanceof Error?e.message:"重置失败"}};
 onMounted(()=>void load());return{positions,selectedPositionId,selectedPosition,selected,activeKey,activeMeta,groups,hiddenCount,diffOpen,saving,added,removed,label:permissionLabel,loadPosition,toggle,openDiff,save,confirmReset,error,message,GROUP_ORDER};
}});
</script>
<style scoped>
.rbac-page{height:100%;min-height:0;overflow-y:auto;box-sizing:border-box;padding:20px;display:flex;flex-direction:column;gap:14px;background:#f7fafd;color:#14263f}.page-head{display:flex;align-items:flex-end;justify-content:space-between;gap:20px}.page-head a{color:#2f7dd0;font-size:13px;text-decoration:none}.page-head h2{margin:6px 0 0}.object-switch{display:flex;align-items:center;gap:10px}.object-badge{min-width:260px;padding:10px 14px;border:2px solid #2f7dd0;border-radius:12px;background:#fff;box-shadow:0 5px 16px rgba(47,125,208,.13)}.object-badge small{display:block;color:#2f7dd0;font-weight:800}.object-badge strong{display:block;margin-top:3px}.object-switch select{height:42px;max-width:260px;border:1px solid #cfe0f5;border-radius:9px;padding:0 10px;color:#14263f;background:#fff}.panel{background:#fff;border:1px solid #d7e3f2;border-radius:16px;box-shadow:0 4px 14px rgba(20,38,63,.06)}.workbench{display:grid;grid-template-columns:minmax(0,1fr) 310px;padding:18px;gap:18px}.permission-pane{min-width:0}.pane-title>div{display:flex;flex-direction:column;gap:3px}.pane-title span{color:#718297;font-size:12px}.boundary-note{margin:12px 0;padding:9px 12px;border:1px dashed #91afd1;border-radius:9px;color:#55708d;background:#f7fafd;font-size:13px}.permission-groups{display:grid;gap:14px;max-height:540px;overflow:auto;padding-right:6px}.permission-groups h3{margin:0 0 7px;color:#55708d;font-size:12px}.permission-list{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:8px}.permission-item{display:flex;align-items:center;gap:8px;min-height:38px;padding:7px 10px;border:1px solid #d7e3f2;border-radius:9px;cursor:pointer}.permission-item.active{border-color:#2f7dd0;background:#f1f6fd}.permission-item input{accent-color:#2f7dd0}.actions{display:flex;gap:10px;margin-top:16px}.danger-button{color:#9b5700}.help{align-self:start;position:sticky;top:0;padding:16px;border:1px solid #d7e3f2;border-radius:12px;background:#f7fafd}.help>strong{color:#55708d;font-size:12px}.help h3{margin:14px 0 5px}.help code{color:#2263ad;background:#e6eff9;padding:3px 7px;border-radius:6px}.help p,.boundary{color:#4e6680;font-size:13px;line-height:1.65}.boundary{padding-top:10px;border-top:1px solid #d7e3f2}.warning{margin-top:10px;padding:9px;background:#fff3d8;border-radius:8px;color:#9b5700;font-size:12px;font-weight:800}.empty{color:#8090a3}.banner{padding:10px 12px;border:1px solid #cfe0f5;border-radius:9px;background:#eaf3fd;color:#1e5aa0}.banner--error{border-color:#fecaca;background:#fef2f2;color:#991b1b}@media(max-width:1000px){.page-head{align-items:stretch;flex-direction:column}.object-switch{align-items:stretch;flex-direction:column}.workbench{grid-template-columns:1fr}.help{position:static}}
</style>
